spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

server:
  port: 1112

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot: INFO
    # org.springframework.security.web.access.ExceptionTranslationFilter: DEBUG
    # org.springframework.security.web.FilterChainProxy: DEBUG
    # org.springframework.security.web.authentication: DEBUG
    # org.springframework.security.web.access.intercept.FilterSecurityInterceptor: DEBUG
    # org.springframework.security.access.intercept.AbstractSecurityInterceptor: DEBUG
