# TODO:
# Add .env stuff, add dev and prod for properties (profiles) yml files
# Add dockerfiles instead of just Dockerfile.dev

services:
  postgres:
    image: postgres:17-alpine
    container_name: dpsn_postgres
    restart: unless-stopped
    env_file:
      - ./db/.env.development
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - localnet

  pgweb:
    image: sosedoff/pgweb
    container_name: dpsn_pgweb
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://dpsn:dpsn@postgres:5432/dpsn_db?sslmode=disable
    depends_on:
      - postgres
    networks:
      - localnet

  eureka-server:
    container_name: dpsn_eureka_server
    build:
      context: ./backend/eureka-server
      dockerfile: Dockerfile.dev
    ports:
      - "8761:8761"
    volumes:
      - ./backend/eureka-server:/app
      - ~/.m2:/root/.m2
    command: "mvn spring-boot:run -Dspring.profiles.active=dev"
    networks:
      - localnet

  api-gateway:
    container_name: dpsn_api_gateway
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - "1110:1110"
    environment:
      - EUREKA_SERVICE_URL=http://eureka-server:8761/eureka/
    volumes:
      - ./backend/api-gateway:/app
      - ~/.m2:/root/.m2
    command: "mvn spring-boot:run -Dspring.profiles.active=dev"
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - localnet

  auth-service:
    container_name: dpsn_auth_service
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile.dev
    ports:
      - "1111:1111"
    environment:
      - EUREKA_SERVICE_URL=http://eureka-server:8761/eureka/
    volumes:
      - ./backend/auth-service:/app
      - ~/.m2:/root/.m2
    command: "mvn spring-boot:run -Dspring.profiles.active=dev"
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - localnet

volumes:
  db:

networks:
  localnet:
    driver: bridge
