# This is just example not prod ready :D
services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-net

  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=${DB_URL}
    networks:
      - db-net

volumes:
  postgres_data:

networks:
  db-net:
